<a href="https://colab.research.google.com/github/Ranjani94/Deep_Learning/blob/master/Ungraded_Assignment_4/pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Chapter 2: 

1. Tensor Fundamentals
2. Numeric Types
3. Numpy interoperability
4. Serializing tensors
5. Moving tensors to GPU
6. Tensor API

In [84]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)
root_dir = "/content/gdrive/My Drive/"
base_dir = root_dir + 'Deep_Learning/'

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [26]:
import torch

a = [1.0, 2.0, 1.0]
a[0]

1.0

In [27]:
a[2] = 3.0
a

[1.0, 2.0, 3.0]

In [28]:
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [29]:
a[1]

tensor(1.)

In [30]:
float(a[1])

1.0

In [31]:
a[2]= 2.0
a

tensor([1., 1., 2.])

In [0]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [33]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [34]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [35]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [36]:
points.shape

torch.Size([3, 2])

In [37]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [39]:
points[0, 1]

tensor(1.)

In [40]:
points[0]

tensor([4., 1.])

In [41]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [42]:
points_storage = points.storage()
points_storage[0]

4.0

In [43]:
points.storage()[1]

1.0

In [44]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [45]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [46]:
second_point.size()

torch.Size([2])

In [47]:
second_point.shape

torch.Size([2])

In [48]:
points.stride()

(2, 1)

In [49]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [50]:
second_point.storage_offset()

2

In [51]:
second_point.stride()

(1,)

In [52]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [53]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [54]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [55]:

points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [56]:
id(points.storage()) == id(points_t.storage())

True

In [57]:
points.stride()

(2, 1)

In [58]:
points_t.stride()

(1, 2)

In [59]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [60]:

transpose_t.shape

torch.Size([5, 4, 3])

In [61]:

some_t.stride()

(20, 5, 1)

In [62]:
transpose_t.stride()

(1, 5, 20)

In [63]:
points.is_contiguous()


True

In [64]:
points_t.is_contiguous()

False

In [65]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [66]:

points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [67]:
points_t.stride()

(1, 2)

In [68]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [69]:
points_t_cont.stride()

(3, 1)

In [70]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.FloatStorage of size 6]

In [0]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [72]:
short_points.dtype

torch.int16

In [0]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [0]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [75]:

points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short  # works from PyTorch 1.3 onwards

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [0]:
# reset points back to original value
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [77]:

some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>

[1, 3]

In [78]:

points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [79]:

points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [0]:

points = torch.from_numpy(points_np)

In [0]:
torch.save(points, '/ourpoints.t')

In [0]:
with open('.ourpoints.t','wb') as f:
   torch.save(points, f)

In [0]:
points = torch.load('/ourpoints.t')

In [0]:
with open('/ourpoints.t','rb') as f:
   points = torch.load(f)

In [0]:
import h5py

f = h5py.File('/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

In [0]:
f = h5py.File('/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]

In [0]:
last_points = torch.from_numpy(dset[-2:])
f.close()

In [0]:

points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

In [0]:
points_gpu = points.to(device='cuda')

In [0]:
points_gpu = points.to(device='cuda:0')

In [0]:
points = 2 * points  # <1>
points_gpu = 2 * points.to(device='cuda') 

In [0]:
points_gpu = points_gpu + 4

In [0]:
points_cpu = points_gpu.to(device='cpu')

In [0]:
points_gpu = points.cuda()  # <1>
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

In [102]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [103]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [0]:
a = torch.ones(3, 2)

In [105]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])