<a href="https://colab.research.google.com/github/Ranjani94/Deep_Learning/blob/master/homework0/Numpy_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Basics of numpy array

In [0]:
import numpy as np 
  
# Creating array object 
arr = np.array( [[ 1, 2, 3], 
                 [ 4, 2, 5]] ) 
print("Array is of type: ", type(arr))  
print("No. of dimensions: ", arr.ndim) 
print("Shape of array: ", arr.shape) 
print("Array stores elements of type: ", arr.dtype) 

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Array stores elements of type:  int64


In [0]:
import numpy as np
np.random.seed(0) 
x1 = np.random.randint(10, size=4)  
x2 = np.random.randint(10, size=(3, 4))  
x3 = np.random.randint(10, size=(3, 4, 5))  
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [0]:
print("dtype:", x3.dtype)

dtype: int64


In [0]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [0]:
x1

array([5, 0, 3, 3])

In [0]:
x1[3]

3

In [0]:
x1[-1]

3

#One-dimensional subarrays

In [0]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
x[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [0]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
x[5:10]

array([5, 6, 7, 8, 9])

In [0]:
x[::5]

array([ 0,  5, 10, 15])

In [0]:
x[1::4]

array([ 1,  5,  9, 13, 17])

#Multidimensional array

In [0]:
x2

array([[7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6]])

In [0]:
x2[:2, :3]

array([[7, 9, 3],
       [2, 4, 7]])

In [0]:
x2[:3, ::2] 

array([[7, 3],
       [2, 7],
       [8, 1]])

In [0]:
x2[::-1, ::-1]

array([[6, 1, 8, 8],
       [6, 7, 4, 2],
       [5, 3, 9, 7]])

#Array Row and column

In [0]:
print(x2[:, 0])

[7 2 8]


In [0]:
print(x2[0, :])

[7 9 3 5]


In [0]:
print(x2[0])

[7 9 3 5]


In [0]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[7 9]
 [2 4]]


In [0]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  9]
 [ 2  4]]


In [0]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  9]
 [ 2  4]]


In [0]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [0]:
x[np.newaxis, :]

array([[1, 2, 3]])

#Concatenation of arrays


In [0]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [0]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [0]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [0]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

#splitting of arrays

In [0]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [0]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [0]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [0]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
